### PR TITLE
KREFLECTION.argv

### PR DESCRIPTION
**Pull request by h0nzZik**
@dwightguth What would be the best way to automatically test this? I tested it only manually, using hardcoded values for the two variables.

### CODE REVIEW

**Review by dwightguth — CHANGES_REQUESTED** [review]
It seems to me that you need to insert an injection above the strings in argv. I would just test it with unit tests if it were me.

**Comment by ehildenb** [comment]
Just curious, why is this in KREFLECTION and not in something like K-IO, or even a separate module K-ARG?

KREFLECTION seems to be about getting at the internal state of the backend at runtime. argv/argc seems more about input.

**Review by dwightguth — APPROVED** [review]
I've approved, but you may want to wait to merge until you've tested it with the c semantics, just in case.

**Comment by h0nzZik** [comment]
@dwightguth I tested it, please merge (I do not have access rights).

**Review by dwightguth — APPROVED** [review]

**Pull request merged**
