### PR TITLE
Cleanup cmake and nix

### PR DESCRIPTION
**Pull request by jonringer**
Eventually I would like to flakify this repository. However, thought the scope of that would be a little too big. So I'm creating this PR which should be a smaller refactor of the existing code. But sill be much more compatible with a flake as most of the complexity is delegated to overlays, rather than having a lot of logic in default.nix

cc @ttuegel

### CODE REVIEW

**Comment by dwightguth** [comment]
I am not a Nix expert and Tom Tuegel is no longer at Runtime Verification, but IOG is the primary consumer of our nix expressions, and the changes to cmake seem fine to me, so if these changes to the nix files are acceptable to me, I have no objections. I would like to have some confirmation that the modified code is compatible with downstream nix expressions before this is merged though. Did you test the k frontend and iele?

**Comment by jonringer** [comment]
not sure why the nix:maven step is paused, but this produces the same derivations that were available before. (this shouldn't have changed anything that other repositories expect.)

Not sure who else can test nix changes.

**Comment by dwightguth** [comment]
Try pushing to the branch again. It's possible because that job runs on pushes and not prs that it didn't interact intelligently with the GitHub logic for requiring approval to run workflows from forks.

**Comment by dwightguth** [comment]
It seems that this didn't fix the issue about the maven check. I did some digging and it seems that workflow doesn't support prs from forks anyway. We probably need to address this somehow eventually, but for now, I'm going to approve this and merge it despite the yellow check, once the other checks pass, because that check wouldn't do anything anyway to a pr that doesn't touch maven at all.

**Review by dwightguth — APPROVED** [review]

**Pull request merged**
