### PR TITLE
Faster parsing - cache calls to `getTagForSymbolName`

### PR DESCRIPTION
**Pull request by h0nzZik**
Using std::map as the cache was sufficient. I wanted to try some prefix/radix tree, but with this change, all the parsing time is spent elsewhere, so I didn't try it.

### CODE REVIEW

**Review by dwightguth — COMMENTED** [review]
If this works and solves the performance issue, I guess I'm not opposed per se. But this seems like a much more inefficient solution than what I thought you were going to do, which was to just at compilation time, build a std::unordered_map that is used as the implementation of getTagForSymbolName rather than the if/else chain that uses strcmp. Then getTagForSymbolName would be amortized O(1) in the number of symbols in the definition rather than O(n). Then you wouldn't need to cache the results of the function because the function itself would be as fast as what you're currently using for the cache.

Is there a particular reason you didn't go for that approach?

**Comment by h0nzZik** [comment]
I didn't try any compile-time approach because it seemed to me to be more complex. I wanted to try the simplest solution that might reduce the problem - and this caching made it disappear.

**Comment by dwightguth** [comment]
Alright. I would only suggest one change to this pr, then. The `getTagForSymbolName` symbol should refer to the cached version, not the uncached version.

**Comment by h0nzZik** [comment]
@dwightguth Would renaming the generated `getTagForSymbolName` into `_getTagForSymbolName` and having a global cache work? I assume there is no threading involved.

**Comment by dwightguth** [comment]
I mean, not with that name, no. C/C++ has undefined behavior if a global variable or function starts with an underscore followed by a lowercase letter. But in general, renaming the function ought to work. I would make the cache thread-local though just to be on the safe side. There is no threading within the interpreter itself, but if you have a global cache and someone tries to embed an interpreter into a threaded application, then you're going to end up racing on accesses to the cache. In general we want to support cases like that, so making the cache thread-local is a good idea. But it should just be a matter of adding the `thread_local` specifier to the variable.

**Comment by dwightguth** [comment]
I will take this over since @h0nzZik is no longer working on RV-Match.

**Review by theo25 — APPROVED** [review]
Approved.

**Pull request merged**
