### PR TITLE
Garbage collection for the old generation

### PR DESCRIPTION
**Pull request by theo25**
This PR implements a garbage collection for the old generation. It uses the same copy-collector infrastructure for the old generation. For now, the old generation is collected every 10 young generation collections. We can change this in future by adding desirable logic in the `shouldCollectOldGen` function. It is tested with the EVM vm and blockchain tests.

### CODE REVIEW

**Comment by dwightguth** [comment]
Once every ten collections might be too often. Have you measured the before/after of the gc overhead?

**Comment by theo25** [comment]
No I haven't. Can you suggest which test should I use as a benchmark for this kind of measurement?

**Comment by theo25** [comment]
These are the time measurements for the blockchain tests, done on my laptop (Intel Core i7-6500U CPU @ 2.50GHz, 12GB memory).

master branch:
```
real 23m54.506s
user 12m39.724s
sys   3m52.104s
```

gc-old branch:
```
real 32m1.973s
user 14m19.712s
sys   4m18.388s
```

I skipped `tests/ethereum-tests/BlockchainTests/GeneralStateTests/stSpecialTest/JUMPDEST_AttackwithJump_d0g0v0.json` because it thrashes my memory.

**Comment by dwightguth** [comment]
I'm suspicious of these timing numbers because one of them shows a much higher wall time but no corresponding increase in user or system time. Are you sure you didn't have anything running in the background when you ran the gc-old branch?

**Comment by theo25** [comment]
I repeated the measurements after setting the frequency of collection for the old generation to once every 50 young generation collections (from once every 10). Here are the new resutls:

master branch:

real 23m36.456s
user 12m41.164s
sys   3m52.752s

gc-old branch:

real 25m50.217s
user 14m24.944s
sys   4m4.368s

This looks like a significant improvement over the previous timings, although still it introduces a slowdown as was expected

**Comment by dwightguth** [comment]
25 minutes instead of 23 is probably acceptable. Hopefully when the peak memory usage goes down we will see a significant drop in system time which will make up for the increased overhead.

**Pull request merged**
