### PR TITLE
install instructions

### PR DESCRIPTION
**Pull request by dwightguth**

### CODE REVIEW

**Comment by PhilMiller** [comment]
You should also mention use of the flag `--backend llvm` when compiling a definition, and the common variable in at least the examples in `k/k-distribution` expecting that to be set in `KOMPILE_FLAGS`

**Comment by dwightguth** [comment]
These are the install instructions for the llvm backend. How to use the backend with the k frontend is a good topic of documentation but I don't think it belongs here in particular.

**Comment by dwightguth** [comment]
It's a dependency of llvm's static libraries.

**Comment by bmmoore** [comment]
Shouldn't it be a dependency of the llvm-6.0 package then?

**Comment by bmmoore** [comment]
Ah, `-l tinfo` seems to work as well as `-l ncurses`, and libtinfo is among the dependencies of the llvm package.

**Pull request merged**
