### PR TITLE
Merged the haste code to the repository

### PR DESCRIPTION
**Pull request by raduom**

### CODE REVIEW

**Comment by dwightguth** [comment]
Jenkins: add to whitelist

**Comment by dwightguth** [comment]
Jenkins: ok to test

**Comment by dwightguth** [comment]
Jenkins: test this please

**Comment by dwightguth** [comment]
Not sure what is wrong with Jenkins. @raduom can you please accept the GitHub invite I sent you in case that fixes this?

**Comment by raduom** [comment]
I do not have any invite.

**Pull request closed without merging**
